name: Build PDF with Pandoc

on:
  


on:
  workflow_dispatch:
  push:
    branches:
      - master
      - pandoc_action
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up TeX Live
      run: |
        sudo apt-get update
        sudo apt-get install -y texlive-xetex texlive-fonts-recommended texlive-plain-generic

    - name: Install Pandoc
      run: sudo apt-get install -y pandoc

    - name: Build PDF
      run: make all
    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: document-artifacts
        path: |
          datamodel_de.pdf
          datamodel_fr.pdf 
          datamodel_de.docx
          datamodel_fr.docx
