name: Uploading release assets


on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release assets
        uses: softprops/action-gh-release@v2
        with:
          files: |
            Release.txt
            output/datamodel_de.pdf
            output/datamodel_fr.pdf
