name: Uploading release assets


on:
  push:
    tags:
      - "v*.*.*"



jobs:
  build:
    uses: ./.github/workflows/build.yaml  # use the callable build job to run build
  release:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    steps:
      - name: Download assets from build
        uses: actions/download-artifact@v4
        with:
          name: document-artifacts
      - name: Release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            output/datamodel_de.pdf
            output/datamodel_fr.pdf
            output/datamodel_de.docx
            output/datamodel_fr.docx
            output/ER-GCOVER.svg
            output/ER-GCOVER.pdf
            exports/coded_domains.xlsx
            exports/all_geolcode.xlsx

