name: Uploading release assets


on:
  push:
    tags:
      - "v*.*.*"



jobs:
  build:
    uses: ./.github/workflows/build.yml  # use the callable build job to run build
  release:
    runs-on: ubuntu-latest
    needs: [build]  # require build to pass before deploy runs
    steps:
      - name: Build
        run: echo ${{ github.sha }} > Release.txt
      - name: Test
        run: cat Release.txt
      - name: Release assets
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
        with:
          files: |
            Release.txt
            output/datamodel_de.pdf
            output/datamodel_fr.pdf
            output/datamodel_de.docx
            output/datamodel_fr.docx
            output/ER-GCOVER.svg
